const App = (S_1) => null;
const App_new = (S_1) => (init_2) => (tick_3) => (when_4) => (P_5) => (new_6) => new_6(init_2)(tick_3)(when_4);
const Char = null;
const GameState = null;
const GameState_draw = (board_1) => (P_2) => (inProgress_3) => (draw_4) => (winner_5) => draw_4(board_1);
const GameState_inProgress = (currentPlayer_1) => (cursorPosition_2) => (board_3) => (P_4) => (inProgress_5) => (draw_6) => (winner_7) => inProgress_5(currentPlayer_1)(cursorPosition_2)(board_3);
const GameState_match = (P_1) => (inProgress_2) => (draw_3) => (winner_4) => (gameState_5) => gameState_5(P_1)(inProgress_2)(draw_3)(winner_4);
const GameState_moveCursor = (state_1) => (() => { const state_P_2 = null; return (() => { const state_inProgress_3 = (state_currentPlayer_3) => (state_cursorPosition_4) => (state_board_5) => GameState_inProgress(state_currentPlayer_3)(Pair_mapFst(null)(null)(null)(state_cursorPosition_4)((x_6) => Math.floor(1 + x_6)))(state_board_5); return (() => { const state_draw_4 = (state_board_4) => state_1; return (() => { const state_winner_5 = (state_player_5) => (state_board_6) => state_1; return GameState_match(state_P_2)(state_inProgress_3)(state_draw_4)(state_winner_5)(state_1); })(); })(); })(); })();
const GameState_winner = (player_1) => (board_2) => (P_3) => (inProgress_4) => (draw_5) => (winner_6) => winner_6(player_1)(board_2);
const List = (T_1) => null;
const List_cons = (T_1) => (head_2) => (tail_3) => (P_4) => (cons_5) => (nil_6) => cons_5(head_2)(tail_3);
const List_nil = (T_1) => (P_2) => (cons_3) => (nil_4) => nil_4;
const Move = null;
const Move_new = (player_1) => (cell_2) => (P_3) => (new_4) => new_4(player_1)(cell_2);
const Nat = null;
const Nat_succ = (n_1) => (P_2) => (succ_3) => (zero_4) => succ_3(n_1);
const Nat_zero = (P_1) => (succ_2) => (zero_3) => zero_3;
const Pair = (A_1) => (B_2) => null;
const Pair_mapFst = (A_1) => (B_2) => (T_3) => (p_4) => (f_5) => (() => { const p_P_6 = null; return (() => { const p_new_7 = (p_fst_7) => (p_snd_8) => Pair_new(T_3)(B_2)(f_5(p_fst_7))(p_snd_8); return Pair_match(null)(null)(p_P_6)(p_new_7)(p_4); })(); })();
const Pair_match = (A_1) => (B_2) => (P_3) => (new_4) => (pair_5) => pair_5(P_3)(new_4);
const Pair_new = (A_1) => (B_2) => (a_3) => (b_4) => (P_5) => (new_6) => new_6(a_3)(b_4);
const Player = null;
const Player_o = (P_1) => (x_2) => (o_3) => o_3;
const Player_x = (P_1) => (x_2) => (o_3) => x_2;
const String = List(Char);
const String_cons = (head_1) => (tail_2) => (P_3) => (cons_4) => (nil_5) => cons_4(head_1)(tail_2);
const String_nil = (P_1) => (cons_2) => (nil_3) => nil_3;
const U48_if = (P_1) => (x_2) => (t_3) => (f_4) => (() => { const x_5_1 = x_2; switch (x_5_1) { case 0: return f_4; default: return ((x_5_1 => (() => { const x_1_6 = x_5_1; return t_3; })())((x_5_1) - 1)); } })();
const main = (() => { const init_1 = GameState_inProgress(Player_x)(Pair_new(null)(null)(0)(0))(List_cons(null)(Move_new(Player_x)(Pair_new(null)(null)(0)(0)))(List_cons(null)(Move_new(Player_x)(Pair_new(null)(null)(1)(1)))(List_cons(null)(Move_new(Player_x)(Pair_new(null)(null)(2)(2)))(List_cons(null)(Move_new(Player_o)(Pair_new(null)(null)(0)(1)))(List_cons(null)(Move_new(Player_o)(Pair_new(null)(null)(2)(0)))(List_nil(null))))))); return (() => { const tick_2 = (state_2) => state_2; return (() => { const when_3 = (key_3) => (state_4) => (() => { const state_P_5 = null; return (() => { const state_inProgress_6 = (state_currentPlayer_6) => (state_cursorPosition_7) => (state_board_8) => U48_if(null)(Math.floor(key_3 === 37))(GameState_moveCursor(state_4))(state_4); return (() => { const state_draw_7 = (state_board_7) => state_4; return (() => { const state_winner_8 = (state_player_8) => (state_board_9) => state_4; return GameState_match(state_P_5)(state_inProgress_6)(state_draw_7)(state_winner_8)(state_4); })(); })(); })(); })(); return App_new(null)(init_1)(tick_2)(when_3); })(); })(); })();

